name: avantassel
favicon: null
layout_spectrum: 1
typography_spectrum: 0.62623
title: Andrew Van Tassel
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#283627'
    - '#dccccc'
    - '#6c5b53'
    - '#b8988b'
    - '#6c825b'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.625
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: null
    url: null
